# Generated by Django 5.1.1 on 2024-09-24 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=15, null=True)),
                ('snum', models.TextField(blank=True, max_length=15, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a hw Model', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Laptop / desktop etc', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.department')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.location')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=20, verbose_name='Hostname')),
                ('serialn', models.CharField(blank=True, max_length=30, null=True, verbose_name='S/N')),
                ('status', models.CharField(blank=True, choices=[('0', 'Received'), ('1', 'Deployed'), ('2', 'Inactive'), ('3', 'In Stock'), ('4', 'Decommission'), ('5', 'Disposed')], default='0', help_text='Asset Status', max_length=1)),
                ('substatus', models.CharField(blank=True, choices=[('0', 'Completed Shipment'), ('1', 'Functional'), ('2', 'Not In use'), ('3', 'In Inventory'), ('4', 'Decommissioned'), ('5', 'Disposed')], default='0', help_text='Asset Sub Status', max_length=1)),
                ('tag', models.CharField(blank=True, max_length=10, null=True)),
                ('buydate', models.DateField(blank=True, null=True, verbose_name='Purchase date')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Enter a job description of the Device', max_length=1000, null=True)),
                ('warranty', models.DateField(blank=True, null=True, verbose_name='Warranty End')),
                ('cost', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.customer')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.location')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.model')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.type')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(choices=[('1', 'Deploy'), ('2', 'Stock'), ('3', 'Refresh'), ('4', 'Stolen')], default='1', max_length=10, verbose_name='Reason')),
                ('name', models.CharField(max_length=50)),
                ('credate', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cus2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.customer', verbose_name='To')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.customer', verbose_name='From')),
                ('deptin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.department', verbose_name='Get')),
                ('deptout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.department', verbose_name='Out')),
                ('equip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.device', verbose_name='Device')),
                ('equip1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.device', verbose_name='Device 2')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=20, verbose_name='Hostname')),
                ('serialn', models.CharField(blank=True, max_length=30, null=True, verbose_name='S/N')),
                ('status', models.CharField(blank=True, choices=[('0', 'Received'), ('1', 'Deployed'), ('2', 'Inactive'), ('3', 'In Stock'), ('4', 'Decommission'), ('5', 'Disposed')], default='0', help_text='Asset Status', max_length=1)),
                ('substatus', models.CharField(blank=True, choices=[('0', 'Completed Shipment'), ('1', 'Functional'), ('2', 'Not In use'), ('3', 'In Inventory'), ('4', 'Decommissioned'), ('5', 'Disposed')], default='0', help_text='Asset Sub Status', max_length=1)),
                ('tag', models.CharField(blank=True, max_length=10, null=True)),
                ('buydate', models.DateField(blank=True, null=True, verbose_name='Purchase date')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Enter a job description of the Device', max_length=1000, null=True)),
                ('warranty', models.DateField(blank=True, null=True, verbose_name='Warranty End')),
                ('cost', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.customer')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.location')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.model')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.type')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
    ]
